## Problem Statement : To predict the survival rate in Titanic Ship Crash using Decision Tree Classifier

In [4]:
#Import required libraries
import pandas as pd
import numpy as np
import seaborn as sns

In [5]:
#Load/Import the dataset
data=pd.read_csv("Titanic.csv")
data.head(5)

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Survived  
0  34.5      0      0   330911   7.8292   NaN        Q         0  
1  47.0      1      0   363272   7.0000   NaN        S         1  
2  62.0      0      0   240276   9.6875   NaN        Q         0  
3  27.0      0      0   315154   8.6625   NaN        S         0  
4  22.0      1      1  3101298  12.2875   NaN        S         1

In [6]:
#Explore Dataset

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
 11  Survived     418 non-null    int64  
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB


In [8]:
data.shape

(418, 12)

In [9]:
data.describe()

PassengerId      Pclass         Age       SibSp       Parch  \
count   418.000000  418.000000  332.000000  418.000000  418.000000   
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   
std     120.810458    0.841838   14.181209    0.896760    0.981429   
min     892.000000    1.000000    0.170000    0.000000    0.000000   
25%     996.250000    1.000000   21.000000    0.000000    0.000000   
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   
max    1309.000000    3.000000   76.000000    8.000000    9.000000   

             Fare    Survived  
count  417.000000  418.000000  
mean    35.627188    0.363636  
std     55.907576    0.481622  
min      0.000000    0.000000  
25%      7.895800    0.000000  
50%     14.454200    0.000000  
75%     31.500000    1.000000  
max    512.329200    1.000000

In [15]:
#Data Cleaning /Find Missiing data

In [16]:
data.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
Survived         0
dtype: int64

In [17]:
#Age coulmn has missing data
#replace null values with mean value of age
data.Age = data.Age.fillna(data.Age.mean())

In [18]:
data.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
Survived         0
dtype: int64

In [19]:
data.Fare=data.Fare.fillna(data.Fare.mean())

In [20]:
#Eliminate the features with insignificant information
data.drop(['PassengerId','Name','SibSp','Parch','Ticket','Embarked','Cabin'],axis='columns',inplace=True)
data.head(5)

Pclass     Sex   Age     Fare  Survived
0       3    male  34.5   7.8292         0
1       3  female  47.0   7.0000         1
2       2    male  62.0   9.6875         0
3       3    male  27.0   8.6625         0
4       3  female  22.0  12.2875         1

In [21]:
#Encoding Categorical data
from sklearn.preprocessing import LabelEncoder
le_Sex =LabelEncoder() 

In [22]:
data['gender'] = le_Sex.fit_transform(data['Sex'])
data

Pclass     Sex       Age      Fare  Survived  gender
0         3    male  34.50000    7.8292         0       1
1         3  female  47.00000    7.0000         1       0
2         2    male  62.00000    9.6875         0       1
3         3    male  27.00000    8.6625         0       1
4         3  female  22.00000   12.2875         1       0
..      ...     ...       ...       ...       ...     ...
413       3    male  30.27259    8.0500         0       1
414       1  female  39.00000  108.9000         1       0
415       3    male  38.50000    7.2500         0       1
416       3    male  30.27259    8.0500         0       1
417       3    male  30.27259   22.3583         0       1

[418 rows x 6 columns]

In [23]:
data.drop('Sex',axis='columns',inplace=True)
data

Pclass       Age      Fare  Survived  gender
0         3  34.50000    7.8292         0       1
1         3  47.00000    7.0000         1       0
2         2  62.00000    9.6875         0       1
3         3  27.00000    8.6625         0       1
4         3  22.00000   12.2875         1       0
..      ...       ...       ...       ...     ...
413       3  30.27259    8.0500         0       1
414       1  39.00000  108.9000         1       0
415       3  38.50000    7.2500         0       1
416       3  30.27259    8.0500         0       1
417       3  30.27259   22.3583         0       1

[418 rows x 5 columns]

In [24]:
x=data.drop('Survived',axis='columns')
x

Pclass       Age      Fare  gender
0         3  34.50000    7.8292       1
1         3  47.00000    7.0000       0
2         2  62.00000    9.6875       1
3         3  27.00000    8.6625       1
4         3  22.00000   12.2875       0
..      ...       ...       ...     ...
413       3  30.27259    8.0500       1
414       1  39.00000  108.9000       0
415       3  38.50000    7.2500       1
416       3  30.27259    8.0500       1
417       3  30.27259   22.3583       1

[418 rows x 4 columns]

In [25]:
y=data.Survived
y=y.values.reshape(-1,1)
y.shape

(418, 1)

In [29]:
from sklearn import tree

In [30]:
model = tree.DecisionTreeClassifier(criterion='gini', random_state=0)

In [31]:
model.fit(x,y)

DecisionTreeClassifier(random_state=0)

In [32]:
#Split data into training set and test set

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=0)


In [34]:
#feature Scaling  
from sklearn.preprocessing import StandardScaler    
st= StandardScaler()  
x_train= st.fit_transform(x_train)    
x_test= st.transform(x_test) 

In [36]:
y_train.shape


(334, 1)

In [37]:
y_train.shape


(334, 1)

In [38]:
y_test.shape

(84, 1)

# model.fit(x_train,y_train)

In [39]:
y_pred=model.predict(x_test)
y_pred


C:\Users\Skhot\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0], dtype=int64)

In [40]:
y_test =np.ravel(y_test)
y_test

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0], dtype=int64)

In [41]:
model.score(x_test,y_test)

C:\Users\Skhot\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


1.0

In [42]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        45
           1       1.00      1.00      1.00        39

    accuracy                           1.00        84
   macro avg       1.00      1.00      1.00        84
weighted avg       1.00      1.00      1.00        84



In [43]:
model.predict([[1,55,59.4,1]])

C:\Users\Skhot\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)