In [2]:
#import the numpy library
import numpy as np

In [12]:
 #Create a 1D array of numbers from 0 to 9
arr = np.array(range(10))
print("The array is : ",arr)

The array is :  [0 1 2 3 4 5 6 7 8 9]


In [14]:
#Create a 3×3 NumPy array of all Boolean value Trues
boolarr = np.ones([3,3])
print(" The array with boolean True values : \n" ,boolarr)

 The array with boolean True values : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
#Extract all odd numbers from array of 1-10
arr = np.array(range(1,11))
print("The array is : ",arr)
#slicing the array by step
print("The array with odd numbers : ", arr[::2])

The array is :  [ 1  2  3  4  5  6  7  8  9 10]
The array with odd numbers :  [1 3 5 7 9]


In [18]:
 #Replace all odd numbers in an array of 1-10 with the value -1
arr =np.array(range(1,11))
arr[arr%2 == 1] = -1
print("All odd numbers are replaced by -1 : ",arr)

All odd numbers are replaced by -1 :  [-1  2 -1  4 -1  6 -1  8 -1 10]


In [19]:
#Convert a 1D array to a 2D array with 2 rows

a =np.array([1,2,3,4,5,6,7,8])
b =a.reshape(2,4)
print("Converted array from 1D to 2D : \n ",b)

Converted array from 1D to 2D : 
  [[1 2 3 4]
 [5 6 7 8]]


In [27]:
#Create two arrays a and b, stack these two arrays vertically 

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
#use vstack() to stack horizontally
print("The vertical stack of two arrays is : \n", np.vstack((a,b)))

The vertical stack of two arrays is : 
 [[1 2 3 4]
 [5 6 7 8]]


In [26]:

#use the np.dot and np.sum to calculate totals

a= np.arange(1,10).reshape(3,3)
b= np.arange(1,10).reshape(3,3)
#use np.dot to multiple two arrays
c = np.dot(a,b)
print("Multiplication of two arrays is : \n ",c)
#use np.sum to total 
sum=np.sum(c)
print("The total of the array is : ",sum)


Multiplication of two arrays is : 
  [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
The total of the array is :  729


In [ ]:
#Extension:
#1. Create the following pattern without hardcoding. Use only NumPy functions.
#2. In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating items present in array b
#3. Get all items between 3 and 7 from a and b and sum themtogether

In [11]:
#create an array using array()
a= np.array([1,2,3])
print("The array is :",a)

#create an array with repetitive elements of array a
b= np.repeat(a,3,axis=0)

#use resize to create 3*3 matrix of array a
c = np.resize(a,(3,3))

#use hstack() to place both in horizontal stack
x = np.hstack(b)
y = np.hstack(c)

#use concatenate() to add both arrays together 
z =np.concatenate((x,y))

#use ravel() to put all elements in single line
print("The Expected output is : ",np.ravel(z))



The array is : [1 2 3]
The Expected output is :  [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [22]:
#2. In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating items present in array b

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])

c = np.concatenate((a,b))
x= np.unique(c)
print("Array with duplicates removed : ",x)

Array with duplicates removed  [1 2 3 4 5 6 7 8 9]


In [24]:
#3. Get all items between 3 and 7 from a and b and sum themtogether

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])
#use boolean slicing to get items between 3 and 7
c = a[(a>=3)&(a<7)]
d = b[(b>=3)&(b<7)]

print("The new array 1: ",c)
print("The new array 2: ",d)
print("The sum of array 1 and array 2 is : ",c+d)

The new array 1:  [3 4 5]
The new array 2:  [4 5 6]
The sum of array 1 and array 2 is :  [ 7  9 11]
